export default {
  home: require('../assets/images/ic_home.png'),
  profile: require('../assets/images/ic_user.png'),
  video: require('../assets/images/ic_play.png'),
  book: require('../assets/images/ic_book.png'),
  edutect_image: require('../assets/images/Edutech_Social_Share.jpg'),
  facebook_icon: require('../assets/images/ic_facebook.png'),
  google_icon: require('../assets/images/ic_google.png'),
  logo_edu: require('../assets/images/logo_edu.png'),
  back_arrow: require('../assets/images/back.png'),
  hamburger: require('../assets/images/hamburger.png'),
  share: require('../assets/images/share.png'),
  search: require('../assets/images/magnifying-glass.png'),
  heartOuiline: require('../assets/images/outLineHeart.png'),
  heartFilled: require('../assets/images/filledHeart.png'),
};
